### ISSUE TITLE
VM not booting after importing svmp_vbox.ova

### ISSUE THREAD

**Issue by sirishkalidindi** [SVMP/svmp-overseer#8]
Hi Team,

Successfully built vbox image and imported to Vbox, when starting the vm it hangs as seen in the image
![screenshot from 2016-09-19 15-48-14](https://cloud.githubusercontent.com/assets/6596167/18629062/f2b857e8-7e80-11e6-954d-f05aa80416f3.png)
Can someone help me out....

Thanks in Advance!

Sirish K

**Comment by Bobyuan1015** [comment]
have you solved it . I also suffered the same issue
